spring.application.name=spring-transaction-sample
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=AccountsInfo;encrypt=true;trustServerCertificate=true
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
server.port=8081