version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: springboot-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: auth_test_db
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "3309:3309"

